### PR TITLE
Allow users to use the lib without jQuery

### PR DESCRIPTION
**Pull request by hugohil**
I just rewrite the `jquery.idle.js` file and replaced all the jQuery specific with native js functions.

For the record, I recently had trouble integrating the lib in a project using RequireJs, so here's my contribution :)

### CODE REVIEW

**Comment by hugohil** [comment]
I'm sorry I just noticed I didn't took the time to update the README :/
Tell me if you want me to do so.

p.s: as you can see I also created a `vanilla.html` file to test the behavior (again, it's the same as the jQuery version, except with pure js).

**Comment by kidh0** [comment]
Hi @hugohil, thank you for add this new feature to the plugin. Could you please update the README file with the instructions about how to use se vanilla version? 
About the RequireJS problem, could you create a jsfiddle so I can test (and maybe fix) the problem?

**Comment by hugohil** [comment]
I can't find an easy way to show you the issue with RequireJS unfortunately :/ jsfiddle doesn't allow me to write different files and thus show you what I've done with the requirejs config. (It's a RequireJS project wrapped in an [electron](electron.atom.io) app so things got a bit complicated in terms of module paths etc ... :D ).
I'll make out something when I have time, is this ok with you ?

**Comment by kidh0** [comment]
No problem at all. Just update the README file with the vanilla instructions :)

**Comment by hugohil** [comment]
I just did with 5349b0c :) Tell if I missed something or if it's not clear enough.

**Comment by kidh0** [comment]
Thank you @hugohil, I'll update the npm package too.

**Pull request merged**
